"""ImcFlow Runner Abstraction

This module provides an abstraction layer for running ImcFlow tests with different
simulation backends (py_runner and rtl_runner).

Usage:
    runner = get_runner("py")  # or "rtl"
    runner.setup()
    runner.run(binary_name="tvm_host_runner", gdb_mode="no", test_name="my_test", eval_dir="/path/to/eval")
    runner.collect_logs(log_dest_dir="/path/to/logs", test_name="my_test")
"""

import os
import subprocess
import glob
from abc import ABC, abstractmethod
from typing import Optional


class ImcFlowRunner(ABC):
    """Abstract base class for ImcFlow test runners"""

    @property
    @abstractmethod
    def name(self) -> str:
        """Return the name of this runner"""
        pass

    @property
    @abstractmethod
    def directory_path(self) -> str:
        """Return the absolute path to the runner directory"""
        pass

    @property
    @abstractmethod
    def timeout(self) -> int:
        """Return the timeout in seconds for this runner"""
        pass

    @abstractmethod
    def setup(self) -> None:
        """Perform any necessary setup before running (e.g., VCS compilation)"""
        pass

    @abstractmethod
    def run(self, binary_name: str, gdb_mode: str, test_name: str, eval_dir: str) -> None:
        """Run the simulation

        Args:
            binary_name: Name of the binary to execute (e.g., "tvm_host_runner")
            gdb_mode: "yes" or "no" to enable/disable GDB
            test_name: Name of the test for output directory
            eval_dir: Evaluation directory containing the model

        Raises:
            subprocess.CalledProcessError: If simulation fails
        """
        pass

    @abstractmethod
    def collect_logs(self, log_dest_dir: str, test_name: str) -> None:
        """Collect runner-specific logs to destination directory

        Args:
            log_dest_dir: Destination directory for log files
            test_name: Name of the test (for log naming)
        """
        pass

    @abstractmethod
    def get_output_path(self, test_name: str) -> str:
        """Get the path to the output file generated by this runner

        Args:
            test_name: Name of the test

        Returns:
            Absolute path to output.npy file
        """
        pass

    def cleanup(self) -> None:
        """Perform any cleanup after running (optional, default is no-op)"""
        pass

    def _stream_command_output(self, command: list, cwd: str, log_path: str,
                                timeout: Optional[int] = None) -> None:
        """Helper to run a command and stream output to both terminal and log file

        Args:
            command: Command and arguments to execute
            cwd: Working directory for the command
            log_path: Path to log file
            timeout: Optional timeout in seconds

        Raises:
            subprocess.CalledProcessError: If command fails
            subprocess.TimeoutExpired: If command times out
        """
        with open(log_path, "w") as log_file:
            process = subprocess.Popen(
                command,
                cwd=cwd,
                stdout=subprocess.PIPE,
                stderr=subprocess.STDOUT,
                text=True
            )

            # Stream output line by line to both terminal and log file
            for line in process.stdout:
                print(line, end='')
                log_file.write(line)

            try:
                process.wait(timeout=timeout)
            except subprocess.TimeoutExpired:
                process.kill()
                process.wait()
                raise

            if process.returncode != 0:
                raise subprocess.CalledProcessError(process.returncode, command)


class PyRunner(ImcFlowRunner):
    """Runner for py_runner (Python functional simulation)"""

    @property
    def name(self) -> str:
        return "py_runner"

    @property
    def directory_path(self) -> str:
        return "/root/project/imcflow/pmap/ISA_sim/gem5/tests/imcflow/py_runner"

    @property
    def timeout(self) -> int:
        return 300  # 5 minutes

    def setup(self) -> None:
        """No setup required for py_runner"""
        print(f"🔧 Using {self.name} (Python functional simulation)")
        if not os.path.exists(self.directory_path):
            raise FileNotFoundError(f"py_runner directory not found at: {self.directory_path}")

    def run(self, binary_name: str, gdb_mode: str, test_name: str, eval_dir: str) -> None:
        """Run gem5 simulation with Python functional model

        Args:
            binary_name: Name of the binary to execute
            gdb_mode: "yes" or "no" to enable/disable GDB
            test_name: Name of the test for output directory
            eval_dir: Evaluation directory containing the model
        """
        print(f"\n--- Running gem5+py_sim Simulation ---")

        # Create runner-specific output directory
        output_dir = self.get_output_path(test_name=eval_dir)
        os.makedirs(os.path.dirname(output_dir), exist_ok=True)

        sim_command = ["direnv", "exec", ".", "./run.sh", binary_name, gdb_mode, test_name]
        log_dir = os.path.join(eval_dir, "logs")
        sim_log_path = os.path.join(log_dir, "gem5.log")

        try:
            self._stream_command_output(
                command=sim_command,
                cwd=self.directory_path,
                log_path=sim_log_path,
                timeout=self.timeout
            )
            print(f"✅ Simulation completed, log saved to: {sim_log_path}")
        except subprocess.TimeoutExpired:
            print(f"❌ Simulation timed out after {self.timeout} seconds")
            raise
        except Exception as e:
            print(f"❌ Simulation failed with error: {e}")
            raise

    def collect_logs(self, log_dest_dir: str, test_name: str) -> None:
        """Collect py_runner logs (logs/now*.log)

        Args:
            log_dest_dir: Destination directory for log files
            test_name: Name of the test
        """
        log_pattern = os.path.join(self.directory_path, "logs", "now*.log")
        sim_log_paths = glob.glob(log_pattern)

        for sim_log in sim_log_paths:
            base_name = os.path.basename(sim_log)
            new_log_path = os.path.join(log_dest_dir, base_name)
            os.rename(sim_log, new_log_path)

    def get_output_path(self, test_name: str) -> str:
        """Get the path to py_runner output file

        Args:
            test_name: Name of the test

        Returns:
            Absolute path to output.npy in py_runner test_outputs
        """
        # With runner_name support, outputs are saved to:
        # {eval_dir}/{test_name}/test_outputs/{runner_name}/output.npy
        eval_dir = "/root/project/tvm/tvm_practice/test_imcflow/codegen"
        return os.path.abspath(
            os.path.join(eval_dir, test_name, "test_outputs", self.name, "output.npy")
        )


class RTLRunner(ImcFlowRunner):
    """Runner for rtl_runner (VCS RTL co-simulation)"""

    @property
    def name(self) -> str:
        return "rtl_runner"

    @property
    def directory_path(self) -> str:
        return "/root/project/imcflow/pmap/ISA_sim/gem5/tests/imcflow/rtl_runner"

    @property
    def timeout(self) -> int:
        return 7200  # 2 hours

    def setup(self) -> None:
        """Setup for rtl_runner: compile VCS if needed"""
        print(f"🔧 Using {self.name} (VCS RTL co-simulation)")

        if not os.path.exists(self.directory_path):
            raise FileNotFoundError(f"rtl_runner directory not found at: {self.directory_path}")

        # Check if VCS simulator binary exists
        vcs_binary = os.path.join(self.directory_path, "build", "simv_imcflow_gem5")
        if os.path.exists(vcs_binary):
            print(f"✅ VCS simulator found at: {vcs_binary}")
            return

        # Need to compile VCS
        print(f"⚙️  VCS simulator not found, compiling RTL...")
        compile_command = ["make", "compile"]
        compile_log = os.path.join(self.directory_path, "vcs_compile.log")

        try:
            self._stream_command_output(
                command=compile_command,
                cwd=self.directory_path,
                log_path=compile_log,
                timeout=600  # 10 minutes for compilation
            )
            print(f"✅ VCS compilation successful")
        except subprocess.CalledProcessError as e:
            print(f"❌ VCS compilation failed (exit code {e.returncode})")
            print(f"   Check log at: {compile_log}")
            raise RuntimeError(f"VCS compilation failed. See {compile_log} for details") from e
        except subprocess.TimeoutExpired:
            print(f"❌ VCS compilation timed out after 600 seconds")
            raise RuntimeError("VCS compilation timed out")

    def run(self, binary_name: str, gdb_mode: str, test_name: str, eval_dir: str) -> None:
        """Run gem5 simulation with RTL co-simulation

        Args:
            binary_name: Name of the binary to execute
            gdb_mode: "yes" or "no" to enable/disable GDB
            test_name: Name of the test for output directory
            eval_dir: Evaluation directory containing the model
        """
        print(f"\n--- Running gem5+RTL Simulation (may take hours) ---")

        # Create runner-specific output directory
        output_dir = self.get_output_path(test_name=eval_dir)
        os.makedirs(os.path.dirname(output_dir), exist_ok=True)

        sim_command = ["direnv", "exec", ".", "./run.sh", binary_name, gdb_mode, test_name]
        log_dir = os.path.join(eval_dir, "logs")
        sim_log_path = os.path.join(log_dir, "gem5_rtl.log")

        try:
            self._stream_command_output(
                command=sim_command,
                cwd=self.directory_path,
                log_path=sim_log_path,
                timeout=self.timeout
            )
            print(f"✅ RTL simulation completed, log saved to: {sim_log_path}")
        except subprocess.TimeoutExpired:
            print(f"❌ RTL simulation timed out after {self.timeout} seconds")
            raise
        except Exception as e:
            print(f"❌ RTL simulation failed with error: {e}")
            raise

    def collect_logs(self, log_dest_dir: str, test_name: str) -> None:
        """Collect rtl_runner logs (gem5_output.log, vcs_sim.log, fsim_logs/*)

        Args:
            log_dest_dir: Destination directory for log files
            test_name: Name of the test
        """
        # Collect main gem5 log
        gem5_log = os.path.join(self.directory_path, "logs", "gem5_output.log")
        if os.path.exists(gem5_log):
            dest_path = os.path.join(log_dest_dir, "gem5_output.log")
            os.rename(gem5_log, dest_path)

        # Collect VCS log
        vcs_log = os.path.join(self.directory_path, "logs", "vcs_sim.log")
        if os.path.exists(vcs_log):
            dest_path = os.path.join(log_dest_dir, "vcs_sim.log")
            os.rename(vcs_log, dest_path)

        # Collect FSIM transaction logs (if they exist)
        fsim_log_dir = os.path.join(self.directory_path, "logs", "fsim_logs")
        if os.path.exists(fsim_log_dir):
            fsim_logs = glob.glob(os.path.join(fsim_log_dir, "*"))
            for fsim_log in fsim_logs:
                base_name = os.path.basename(fsim_log)
                dest_path = os.path.join(log_dest_dir, f"fsim_{base_name}")
                os.rename(fsim_log, dest_path)

    def get_output_path(self, test_name: str) -> str:
        """Get the path to rtl_runner output file

        Args:
            test_name: Name of the test

        Returns:
            Absolute path to output.npy in rtl_runner test_outputs
        """
        # With runner_name support, outputs are saved to:
        # {eval_dir}/{test_name}/test_outputs/{runner_name}/output.npy
        eval_dir = "/root/project/tvm/tvm_practice/test_imcflow/codegen"
        return os.path.abspath(
            os.path.join(eval_dir, test_name, "test_outputs", self.name, "output.npy")
        )


def get_runner(runner_type: Optional[str] = None):
    """Factory function to get the appropriate runner(s)

    Args:
        runner_type: Type of runner ("py", "rtl", or "both"). If None, reads from
                     IMCFLOW_RUNNER environment variable (defaults to "py")

    Returns:
        A single ImcFlowRunner instance, or a list of runners if runner_type is "both"

    Raises:
        ValueError: If runner_type is not valid
    """
    if runner_type is None:
        runner_type = os.getenv("IMCFLOW_RUNNER", "py")

    runner_type = runner_type.lower()

    if runner_type == "py":
        return PyRunner()
    elif runner_type == "rtl":
        return RTLRunner()
    elif runner_type == "both":
        return [PyRunner(), RTLRunner()]
    else:
        raise ValueError(
            f"Invalid runner type: '{runner_type}'. "
            f"Valid options are 'py', 'rtl', or 'both'. "
            f"Set via IMCFLOW_RUNNER environment variable or pass to get_runner()"
        )
