"""ImcFlow Runner Abstraction

This module provides an abstraction layer for running ImcFlow tests with different
simulation backends (py_runner and rtl_runner).

Usage:
    runner = get_runner("py")  # or "rtl"
    runner.setup()
    runner.run(binary_name="tvm_host_runner", gdb_mode="no", test_name="my_test", eval_dir="/path/to/eval")
    # Logs are automatically written to eval_dir/logs/runner_name/ during run()
"""

import os
import subprocess
from abc import ABC, abstractmethod
from typing import Optional


class ImcFlowRunner(ABC):
    """Abstract base class for ImcFlow test runners"""

    @property
    @abstractmethod
    def name(self) -> str:
        """Return the name of this runner"""
        pass

    @property
    @abstractmethod
    def directory_path(self) -> str:
        """Return the absolute path to the runner directory"""
        pass

    @property
    @abstractmethod
    def timeout(self) -> int:
        """Return the timeout in seconds for this runner"""
        pass

    @property
    @abstractmethod
    def display_name(self) -> str:
        """Return the display name for this runner (e.g., 'gem5+py_sim Simulation')"""
        pass

    @property
    @abstractmethod
    def main_log_filename(self) -> str:
        """Return the main log filename (e.g., 'gem5.log' or 'gem5_rtl.log')"""
        pass

    @abstractmethod
    def setup(self) -> None:
        """Perform any necessary setup before running (e.g., VCS compilation)"""
        pass

    def run(self, binary_name: str, gdb_mode: str, test_name: str, eval_dir: str, npz_file: str = "") -> None:
        """Run the simulation

        Args:
            binary_name: Name of the binary to execute (e.g., "tvm_host_runner")
            gdb_mode: "yes" or "no" to enable/disable GDB
            test_name: Name of the test for output directory
            eval_dir: Evaluation directory containing the model
            npz_file: Optional NPZ file path to pass to the binary

        Raises:
            subprocess.CalledProcessError: If simulation fails
        """
        print(f"\n--- Running {self.display_name} ---")

        # Create runner-specific output directory
        output_dir = self.get_output_path(test_name=eval_dir)
        os.makedirs(os.path.dirname(output_dir), exist_ok=True)

        # Create runner-specific log directory in test's logs folder
        runner_log_dir = os.path.join(eval_dir, "logs", self.name)
        os.makedirs(runner_log_dir, exist_ok=True)

        # Convert to absolute path since run.sh executes from runner directory
        abs_runner_log_dir = os.path.abspath(runner_log_dir)

        # Pass absolute log directory as 4th argument, NPZ file as 5th (if provided)
        sim_command = ["direnv", "exec", ".", "./run.sh", binary_name, gdb_mode, test_name, abs_runner_log_dir]
        if npz_file:
            # Convert NPZ file path to absolute path since run.sh executes from runner directory
            abs_npz_file = os.path.abspath(npz_file)
            sim_command.append(abs_npz_file)

        try:
            self._stream_command_output(
                command=sim_command,
                cwd=self.directory_path,
                log_path=os.path.join(runner_log_dir, self.main_log_filename),
                timeout=self.timeout
            )
            print(f"✅ Simulation completed")
            print(f"   Logs saved to: {runner_log_dir}/")
        except subprocess.TimeoutExpired:
            print(f"❌ Simulation timed out after {self.timeout} seconds")
            raise
        except Exception as e:
            print(f"❌ Simulation failed with error: {e}")
            raise

    @abstractmethod
    def get_output_path(self, test_name: str) -> str:
        """Get the path to the output file generated by this runner

        Args:
            test_name: Name of the test

        Returns:
            Absolute path to output.npy file
        """
        pass

    def cleanup(self) -> None:
        """Perform any cleanup after running (optional, default is no-op)"""
        pass

    def _stream_command_output(self, command: list, cwd: str, log_path: str,
                                timeout: Optional[int] = None) -> None:
        """Helper to run a command and stream output to both terminal and log file

        Args:
            command: Command and arguments to execute
            cwd: Working directory for the command
            log_path: Path to log file
            timeout: Optional timeout in seconds

        Raises:
            subprocess.CalledProcessError: If command fails
            subprocess.TimeoutExpired: If command times out
        """
        with open(log_path, "w") as log_file:
            process = subprocess.Popen(
                command,
                cwd=cwd,
                stdout=subprocess.PIPE,
                stderr=subprocess.STDOUT,
                text=True
            )

            # Stream output line by line to both terminal and log file
            for line in process.stdout:
                print(line, end='')
                log_file.write(line)

            try:
                process.wait(timeout=timeout)
            except subprocess.TimeoutExpired:
                process.kill()
                process.wait()
                raise
            except KeyboardInterrupt:
                process.kill()
                process.wait()
                raise

            if process.returncode != 0:
                raise subprocess.CalledProcessError(process.returncode, command)


class PyRunner(ImcFlowRunner):
    """Runner for py_runner (Python functional simulation)"""

    @property
    def name(self) -> str:
        return "py_runner"

    @property
    def directory_path(self) -> str:
        return "/root/project/imcflow/pmap/ISA_sim/gem5/tests/imcflow/py_runner"

    @property
    def timeout(self) -> int:
        return 300  # 5 minutes

    @property
    def display_name(self) -> str:
        return "gem5+py_sim Simulation"

    @property
    def main_log_filename(self) -> str:
        return "gem5.log"

    def setup(self) -> None:
        """No setup required for py_runner"""
        print(f"🔧 Using {self.name} (Python functional simulation)")
        if not os.path.exists(self.directory_path):
            raise FileNotFoundError(f"py_runner directory not found at: {self.directory_path}")

    def get_output_path(self, test_name: str) -> str:
        """Get the path to py_runner output file

        Args:
            test_name: Name of the test

        Returns:
            Absolute path to output.npy in py_runner test_outputs
        """
        # With runner_name support, outputs are saved to:
        # {eval_dir}/{test_name}/test_outputs/{runner_name}/output.npy
        eval_dir = "/root/project/tvm/tvm_practice/test_imcflow/codegen"
        return os.path.abspath(
            os.path.join(eval_dir, test_name, "test_outputs", self.name, "output.npy")
        )


class RTLRunner(ImcFlowRunner):
    """Runner for rtl_runner (VCS RTL co-simulation)"""

    @property
    def name(self) -> str:
        return "rtl_runner"

    @property
    def directory_path(self) -> str:
        return "/root/project/imcflow/pmap/ISA_sim/gem5/tests/imcflow/rtl_runner"

    @property
    def timeout(self) -> int:
        return 7200  # 2 hours

    @property
    def display_name(self) -> str:
        return "gem5+RTL Simulation (may take hours)"

    @property
    def main_log_filename(self) -> str:
        return "gem5_rtl.log"

    def setup(self) -> None:
        """Setup for rtl_runner: compile VCS if needed"""
        print(f"🔧 Using {self.name} (VCS RTL co-simulation)")

        if not os.path.exists(self.directory_path):
            raise FileNotFoundError(f"rtl_runner directory not found at: {self.directory_path}")

        # Check if VCS simulator binary exists
        vcs_binary = os.path.join(self.directory_path, "build", "simv_imcflow_gem5")
        if os.path.exists(vcs_binary):
            print(f"✅ VCS simulator found at: {vcs_binary}")
            return

        # Need to compile VCS
        print(f"⚙️  VCS simulator not found, compiling RTL...")
        compile_command = ["direnv", "exec", ".", "make", "compile"]
        compile_log = os.path.join(self.directory_path, "vcs_compile.log")

        try:
            self._stream_command_output(
                command=compile_command,
                cwd=self.directory_path,
                log_path=compile_log,
                timeout=600  # 10 minutes for compilation
            )
            print(f"✅ VCS compilation successful")
        except subprocess.CalledProcessError as e:
            print(f"❌ VCS compilation failed (exit code {e.returncode})")
            print(f"   Check log at: {compile_log}")
            raise RuntimeError(f"VCS compilation failed. See {compile_log} for details") from e
        except subprocess.TimeoutExpired:
            print(f"❌ VCS compilation timed out after 600 seconds")
            raise RuntimeError("VCS compilation timed out")

    def get_output_path(self, test_name: str) -> str:
        """Get the path to rtl_runner output file

        Args:
            test_name: Name of the test

        Returns:
            Absolute path to output.npy in rtl_runner test_outputs
        """
        # With runner_name support, outputs are saved to:
        # {eval_dir}/{test_name}/test_outputs/{runner_name}/output.npy
        eval_dir = "/root/project/tvm/tvm_practice/test_imcflow/codegen"
        return os.path.abspath(
            os.path.join(eval_dir, test_name, "test_outputs", self.name, "output.npy")
        )


def get_runner(runner_type: Optional[str] = None):
    """Factory function to get the appropriate runner(s)

    Args:
        runner_type: Type of runner ("py", "rtl", or "both"). If None, reads from
                     IMCFLOW_RUNNER environment variable (defaults to "py")

    Returns:
        A single ImcFlowRunner instance, or a list of runners if runner_type is "both"

    Raises:
        ValueError: If runner_type is not valid
    """
    if runner_type is None:
        runner_type = os.getenv("IMCFLOW_RUNNER", "py")

    runner_type = runner_type.lower()

    if runner_type == "py":
        return PyRunner()
    elif runner_type == "rtl":
        return RTLRunner()
    elif runner_type == "both":
        return [PyRunner(), RTLRunner()]
    else:
        raise ValueError(
            f"Invalid runner type: '{runner_type}'. "
            f"Valid options are 'py', 'rtl', or 'both'. "
            f"Set via IMCFLOW_RUNNER environment variable or pass to get_runner()"
        )
